# This is a basic workflow to help you get started with Actions

name: Auto Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Changelog:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read the Releases File
        id: changelog
        uses: Jeconias/changelog@v1.3
        with:
          path: "./README.md"  
      - name: Output results
      - run: echo "${{steps.changelog.outputs.changelog}} | ${{steps.changelog.outputs.version}}"
